name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.PAT || github.token }}

      - name: Sync fork with upstream
        run: gh repo sync --force
        env:
          GH_TOKEN: ${{ secrets.PAT || github.token }}
